name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set default.region "${{ secrets.AWS_REGION }}"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to S3 (Boolha)
        run:  aws s3 cp index.html s3://boolha/index.html --endpoint-url=https://s3.amazonaws.com

      - name: Deploy to S3
        run: |
          aws s3 sync ./bolha-devops s3://boolha

      - name: SSH into EC2 Instance and Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /path/to/your/project
            git pull origin main

      - name: Deploy to S3 (Boolha again)
        run: aws s3 cp ./bolha-devops/index.html s3://boolha/index.html --endpoint-url=https://s3.amazonaws.com

      - name: Retry Deployment to S3
        run: aws s3 sync ./bolha-devops s3://boolha
