name: Implantar site estático

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v2

      - name: SSH no Bastion Host e na Instância EC2 e Implantação
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BASTION_HOST_IP }}
          username: ubuntu
          key: ${{ secrets.BASTION_HOST_SSH_KEY }}
          script: |
            # Conecta-se ao Bastion Host
            echo "Conectado ao Bastion Host"

            
            ssh -i ~/Downloads/devop.pem ubuntu@3.82.21.208 'cd /bolha-devops/.github/workflows && git pull origin main'


             
