name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
      
    - name: Configure AWS credentials
      run: 
        aws configure set aws_access_key_id AKIAQ3EGUOB25FFSKBOV

        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ${{ secrets.AWS_REGION }}
      
    - name: Deploy to S3
      run: |
        aws s3 cp ./bolha-devops/index.html s3://boolha/index.html
      
    - name: SSH into EC2 instance and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          scp -i ${{ secrets.EC2_PRIVATE_KEY }} ./bolha-devops/index.html ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/html
