nome: Implantação no S3 (Sincronização)
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        usa: actions/checkout@v2

      - name: Configurar Credenciais da AWS
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Implantar no S3 (Sincronizar)
        run: aws s3 sync . s3://boolha --region us-east-1

      - name: Configurar Bucket S3 para Hospedagem de Site Estático
        run: |
          aws s3 website s3://boolha --index-document index.html

      - name: Carregar Site para S3
        run: aws s3 sync . s3://boolha --delete

      - name: SSH na Instância EC2 e Implantação
        uses: appleboy/ssh-action@master
        with:
          host: 18.234.225.100
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            git pull origin main
            sudo apt-get update
            sudo apt-get install nginx -y
            sudo systemctl restart nginx
